//! Page architecture for Anker (`www.anker.com`).

use crate::parsing::structure::{RetailerArchitecture, collection, comments, json, particle, segment, trash};

pub fn offer_detail_architecture_v1() -> RetailerArchitecture {
    RetailerArchitecture::new(vec![
        comments(),
        trash("svg"),
        trash(r#"script[src^="/_next/"]"#),
        trash(r#"link[href^="/_next/"]"#),
        segment("header#header", "navigation", vec![]),
        segment("footer", "footer", vec![]),
        segment(".footerContent > div[style]", "country_selector", vec![]),
        collection(
            r#"script[type="application/ld+json"]"#,
            "schemas",
            vec![json(
                "script",
                "",
                vec![
                    ("@type", "type"),
                    ("name", "name"),
                    ("description", "description"),
                    ("sku", "sku"),
                    ("gtin", "gtin"),
                    ("image", "images"),
                    ("brand.name", "brand"),
                    ("offers.url", "offer_url"),
                    ("offers.itemCondition", "condition"),
                    ("offers.availability", "availability"),
                    ("offers.price", "price"),
                    ("offers.priceCurrency", "currency"),
                    ("legalName", "legal_name"),
                    ("url", "url"),
                    ("email", "email"),
                    ("sameAs", "same_as"),
                    ("itemListElement[].position", "position"),
                    ("itemListElement[].name", "item_name"),
                    ("itemListElement[].item", "item_url"),
                ],
            )],
        ),
        json(
            "script#__NEXT_DATA__",
            "next_data",
            vec![
                ("locale", "locale"),
                ("page", "page"),
                ("query.slug", "query_slug"),
                ("props.pageProps.pageType", "page_type"),
                ("props.pageProps.slug", "slug"),
                ("props.pageProps.payload.currency", "payload_currency"),
                ("props.pageProps.payload.region", "region"),
                ("props.pageProps.payload.shopify_domain", "shopify_domain"),
                ("props.pageProps.shop.name", "shop_name"),
                ("props.pageProps.shop.paymentSettings.countryCode", "country"),
                ("props.pageProps.shop.paymentSettings.currencyCode", "currency"),
                ("props.pageProps.shop.primaryDomain.url", "shop_url"),
                ("props.pageProps.seo.canonical", "canonical"),
                ("props.pageProps.seo.title", "seo_title"),
                ("props.pageProps.seo.description", "seo_description"),
                ("props.pageProps.product.id", "product_id"),
                ("props.pageProps.product.handle", "handle"),
                ("props.pageProps.product.slug", "product_slug"),
                ("props.pageProps.product.path", "path"),
                ("props.pageProps.product.name", "name"),
                ("props.pageProps.product.title", "title"),
                ("props.pageProps.product.description", "description"),
                ("props.pageProps.product.descriptionHtml", "description_html"),
                ("props.pageProps.product.vendor", "vendor"),
                ("props.pageProps.product.productType", "product_type"),
                ("props.pageProps.product.availableForSale", "available"),
                ("props.pageProps.product.totalInventory", "inventory"),
                ("props.pageProps.product.requiresSellingPlan", "requires_selling_plan"),
                ("props.pageProps.product.publishedAt", "published_at"),
                ("props.pageProps.product.price.value", "price"),
                ("props.pageProps.product.price.currencyCode", "price_currency"),
                ("props.pageProps.product.listPrice", "list_price"),
                ("props.pageProps.product.tags", "tags"),
                ("props.pageProps.product.images[].url", "image_url"),
                ("props.pageProps.product.images[].width", "image_width"),
                ("props.pageProps.product.images[].height", "image_height"),
                ("props.pageProps.product.collections.nodes[].id", "collection_id"),
                (
                    "props.pageProps.product.collections.nodes[].handle",
                    "collection_handle",
                ),
                ("props.pageProps.product.collections.nodes[].title", "collection_title"),
                ("props.pageProps.product.options[].id", "option_id"),
                ("props.pageProps.product.options[].name", "option_name"),
                ("props.pageProps.product.options[].displayName", "option_display_name"),
                ("props.pageProps.product.variants[].id", "variant_id"),
                ("props.pageProps.product.variants[].name", "variant_name"),
                ("props.pageProps.product.variants[].sku", "variant_sku"),
                ("props.pageProps.product.variants[].barcode", "variant_barcode"),
                (
                    "props.pageProps.product.variants[].availableForSale",
                    "variant_available",
                ),
                (
                    "props.pageProps.product.variants[].currentlyNotInStock",
                    "currently_not_in_stock",
                ),
                (
                    "props.pageProps.product.variants[].quantityAvailable",
                    "quantity_available",
                ),
                (
                    "props.pageProps.product.variants[].requiresShipping",
                    "requires_shipping",
                ),
                ("props.pageProps.product.variants[].weight", "weight"),
                ("props.pageProps.product.variants[].price", "variant_price"),
                ("props.pageProps.product.variants[].listPrice", "variant_list_price"),
                ("props.pageProps.product.variants[].image.url", "variant_image_url"),
                ("props.pageProps.product.variants[].image.width", "variant_image_width"),
                (
                    "props.pageProps.product.variants[].image.height",
                    "variant_image_height",
                ),
                (
                    "props.pageProps.product.metafields.productInfos.key_features.list[].key",
                    "feature_key",
                ),
                (
                    "props.pageProps.product.metafields.productInfos.key_features.list[].value",
                    "feature_value",
                ),
            ],
        ),
        segment(
            "body",
            "product",
            vec![
                trash("#boardLogo"),
                trash("header#header"),
                trash("footer"),
                trash(".footerContent"),
                trash("script"),
                particle("h1", "title", vec![("", "value")]),
                particle(
                    ".jdgm-prev-badge",
                    "reviews",
                    vec![
                        ("data-average-rating", "average_rating"),
                        ("data-number-of-reviews", "review_count"),
                        ("data-number-of-questions", "question_count"),
                    ],
                ),
                particle(
                    ".jdgm-review-widget",
                    "reviews_widget",
                    vec![("data-id", "product_id"), ("data-product-title", "product_title")],
                ),
                collection(
                    "img",
                    "images",
                    vec![particle(
                        "",
                        "",
                        vec![
                            ("src", "src"),
                            ("srcset", "srcset"),
                            ("alt", "alt"),
                            ("width", "width"),
                            ("height", "height"),
                            ("loading", "loading"),
                        ],
                    )],
                ),
                collection(
                    "a[href]",
                    "links",
                    vec![particle(
                        "",
                        "",
                        vec![
                            ("href", "url"),
                            ("", "label"),
                            ("title", "title"),
                            ("aria-label", "aria_label"),
                        ],
                    )],
                ),
                collection(
                    "button",
                    "buttons",
                    vec![particle(
                        "",
                        "",
                        vec![
                            ("", "label"),
                            ("type", "type"),
                            ("title", "title"),
                            ("aria-label", "aria_label"),
                        ],
                    )],
                ),
                collection(
                    "input",
                    "inputs",
                    vec![particle(
                        "",
                        "",
                        vec![
                            ("type", "type"),
                            ("name", "name"),
                            ("value", "value"),
                            ("id", "id"),
                            ("checked", "checked"),
                        ],
                    )],
                ),
                particle("", "text", vec![("", "value")]),
            ],
        ),
        segment(
            "head",
            "head",
            vec![
                particle("title", "title", vec![("", "value")]),
                collection(
                    "meta",
                    "meta",
                    vec![particle(
                        "",
                        "",
                        vec![
                            ("charset", "charset"),
                            ("name", "name"),
                            ("property", "property"),
                            ("content", "content"),
                        ],
                    )],
                ),
                collection(
                    "link",
                    "links",
                    vec![particle(
                        "",
                        "",
                        vec![
                            ("rel", "rel"),
                            ("href", "url"),
                            ("hreflang", "hreflang"),
                            ("as", "as"),
                            ("type", "type"),
                            ("crossorigin", "crossorigin"),
                            ("fetchpriority", "fetch_priority"),
                            ("media", "media"),
                        ],
                    )],
                ),
                collection(
                    "script",
                    "scripts",
                    vec![particle(
                        "",
                        "",
                        vec![
                            ("src", "src"),
                            ("type", "type"),
                            ("id", "id"),
                            ("defer", "defer"),
                            ("nomodule", "nomodule"),
                            ("async", "async"),
                            ("", "inline"),
                        ],
                    )],
                ),
                collection(
                    "style",
                    "styles",
                    vec![particle("", "", vec![("id", "id"), ("", "inline")])],
                ),
            ],
        ),
    ])
}
